site_name: Andy Nael's Docs
site_url: !ENV READTHEDOCS_CANONICAL_URL
site_author: Andy Nael
site_description: Tài liệu System Administration, Cloud, Kubernetes và DevOps
repo_name: AndyNael/SRE
repo_url: https://github.com/AndyNael/SRE/
edit_uri: edit/main/docs/
docs_dir: docs
site_dir: site
use_directory_urls: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - mathjax.js

theme:
  name: material
  language: vi
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: purple
      toggle:
        icon: material/weather-night
        name: Chuyển sang giao diện tối
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Chuyển sang giao diện sáng
  features:
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.suggest

plugins:
  - search
  - awesome-pages
  - mkdocs-backlinks
  - roamlinks

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
hooks:
  - hooks/noindex.py